version: "3.5"

services:
  dns:
    image: blockchain
    container_name: dns
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - NODES_FILENAME=/data/dns_nodes.json
    volumes:
      - ./data/dns_nodes.json:/data/dns_nodes.json
    command: /app/cmd/dns/dns
    networks:
      - blockchain

  node-server-1:
    image: blockchain
    container_name: bc_node_1
    depends_on:
      - dns
    ports:
      - 3001:3001
    environment:
      - PORT=3001
    env_file:
      - .node_env
    volumes:
      - ./data/blockchain_1.json:/data/blockchain.json
      - ./data/nodes_1.json:/data/nodes.json
    command: /app/cmd/node/node
    networks:
      - blockchain

  node-server-2:
    image: blockchain
    container_name: bc_node_2
    depends_on:
      - dns
      - node-server-1
    ports:
      - 3002:3002
    environment:
      - PORT=3002
    env_file:
      - .node_env
    volumes:
      - ./data/blockchain_2.json:/data/blockchain.json
      - ./data/nodes_2.json:/data/nodes.json
    command: /app/cmd/node/node
    networks:
      - blockchain

  node-server-3:
    image: blockchain
    container_name: bc_node_3_miner
    depends_on:
      - dns
      - node-server-2
    ports:
      - 3003:3003
    environment:
      - PORT=3003
    env_file:
      - .node_env
    volumes:
      - ./data/blockchain_3.json:/data/blockchain.json
      - ./data/nodes_3.json:/data/nodes.json
    command: /app/cmd/node/node -mine
    networks:
      - blockchain

  node-server-4:
    image: blockchain
    container_name: bc_node_4_miner
    depends_on:
      - dns
      - node-server-3
    ports:
      - 3004:3004
    environment:
      - PORT=3004
    env_file:
      - .node_env
    volumes:
      - ./data/blockchain_4.json:/data/blockchain.json
      - ./data/nodes_4.json:/data/nodes.json
    command: /app/cmd/node/node -mine
    networks:
      - blockchain

  node-server-5:
    image: blockchain
    container_name: bc_node_5_miner
    depends_on:
      - dns
      - node-server-4
    ports:
      - 3005:3005
    environment:
      - PORT=3005
    env_file:
      - .node_env
    volumes:
      - ./data/blockchain_5.json:/data/blockchain.json
      - ./data/nodes_5.json:/data/nodes.json
    command: /app/cmd/node/node -mine
    networks:
      - blockchain

  wallets:
    image: blockchain
    container_name: wallets
    depends_on:
      - dns
      - node-server-5
    ports:
      - 4000:4000
    environment:
      - PORT=4000
      - DNS_HOST=dns
      - DNS_PORT=3000
      - WALLETS_FILENAME=/data/wallets.json
    volumes:
      - ./data/wallets.json:/data/wallets.json
    command: /app/cmd/wallet/wallet -simulate
    networks:
      - blockchain

networks:
  blockchain:
    driver: bridge


